### ISSUE TITLE
Implement Sorting for List

### ISSUE THREAD

**Issue by adarsh-a-tw** [gopinathr143/go-collections#23]
Implement a sort method that sorts elements of a `List` structure based on a comparison function using quicksort sorting algorithm.

Points to be noted:

- The `sort` method should be compatible with any list type and not limited to lists of numbers or strings. Use generics to achieve this.

- The `sort` method should accept three parameters: 
    - `list`, which is the list to be sorted of type `List[T]`. 
    -  `cmp`, which is a comparison function with signature `func(elem1 T, elem2) int` and should return -1.0 or 1 depending on the result of the comparison of the two elements.
    
If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you.

Please take a look at our [CONTRIBUTING.md](https://github.com/gopher-utils/go-collections/blob/main/CONTRIBUTING.md) before you start working on this.

**Comment by Ishwarya-Selvaraj** [comment]
Is it still open @adarsh-a-tw ?

**Comment by adarsh-a-tw** [comment]
@Ishwarya-Selvaraj  Yes, I can assign it to you if you are interested to pick it up.

**Comment by Ishwarya-Selvaraj** [comment]
Yes sure, I'm interested to pick it up
