### ISSUE TITLE
Implement Set

### ISSUE THREAD

**Issue by adarsh-a-tw** [gopinathr143/go-collections#24]
Create a new struct `Set` that follows the interface `Collection` and implement a method `Add` that adds an element to the set.

If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you.

Please take a look at our [CONTRIBUTING.md](https://github.com/gopher-utils/go-collections/blob/main/CONTRIBUTING.md) before you start working on this.

**Comment by zegabr** [comment]
Hi, I might want to work on this. Is it allowed to use the built-in map structure to create the set?
For example, a set of strings could be simply a `map[string]bool`.

If not, how would you recommend to implement it?

**Comment by adarsh-a-tw** [comment]
Hi @zegabr !! You can use the built-in map structure to create the set. I would suggest using `map[]struct{}` rather than using `map[string]bool` as there would be a slight performance increase when using the former.

Ref: [https://itnext.io/set-in-go-map-bool-and-map-struct-performance-comparison-5315b4b107b#:~:text=Although%20map%5B%5Dstruct%7B%7D,uint%2C%20bitset%20is%20more%20recommended.](https://itnext.io/set-in-go-map-bool-and-map-struct-performance-comparison-5315b4b107b#:~:text=Although%20map%5B%5Dstruct%7B%7D,uint%2C%20bitset%20is%20more%20recommended.)

**Comment by zegabr** [comment]
Thanks for the tip @adarsh-a-tw, I'll start working on that probably today
