### ISSUE TITLE
Handle release through workflow

### ISSUE THREAD

**Issue by adarsh-a-tw** [gopinathr143/go-collections#25]
Add a workflow to create a release. The workflow can use [this action](https://github.com/softprops/action-gh-release).

Note:

- The workflow should be triggered when a git tag that starts with `v` is pushed (like `v1.0.1`).
- The release created should be a draft version. This can be done by configuring the mentioned action.
- Release notes should be automatically created from git history.

If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you.

Please take a look at our [CONTRIBUTING.md](https://github.com/gopher-utils/go-collections/blob/main/CONTRIBUTING.md) before you start working on this.

**Comment by JoseAngel1196** [comment]
picking this up

**Comment by aswath-s-tw** [comment]
Hey @JoseAngel1196 , please take a look at [goreleaser,](https://github.com/marketplace/actions/goreleaser-action) they have an action to create releases easily.

**Comment by JoseAngel1196** [comment]
sure, will take a look, can you assign that to me?

**Comment by JoseAngel1196** [comment]
Hey @aswath-s-tw can you please create a `GITHUB_TOKEN` for me. The minimum permissions the GITHUB_TOKEN should have to run this are `write:packages`

**Comment by aswath-s-tw** [comment]
Can you create a personal access token and test it on your fork ? You can attach the workflow run link here so that we can take a look and start a PR.

**Comment by aswath-s-tw** [comment]
Thanks for your contribution @JoseAngel1196. Works like a charm ! 👍🚀
