### ISSUE TITLE
Add codecov to CI/CD and update coverage in README.md

### ISSUE THREAD

**Issue by adarsh-a-tw** [gopinathr143/go-collections#26]
Replace the current tool (basic calculator) with codecov in github actions workflow and show coverage in README.md.

Suggested Gh Action to use: https://github.com/codecov/codecov-action

If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you.

Please take a look at our [CONTRIBUTING.md](https://github.com/gopher-utils/go-collections/blob/main/CONTRIBUTING.md) before you start working on this.

**Comment by JoseAngel1196** [comment]
picking this up

**Comment by adarsh-a-tw** [comment]
@JoseAngel1196 Thanks for picking this up.

**Comment by JoseAngel1196** [comment]
Gonna work on this tomorrow, will let you know if I have any Qs!

**Comment by JoseAngel1196** [comment]
Hey @adarsh-a-tw for some reason I can't push PRs on this repository. Getting this error message:

```
ERROR: Permission to gopher-utils/go-collections.git denied to JoseAngel1196.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by adarsh-a-tw** [comment]
@JoseAngel1196 Please create a fork and work on it.

**Comment by JoseAngel1196** [comment]
Hey @adarsh-a-tw can you pls approve the workflow so i can test it? https://github.com/gopher-utils/go-collections/pull/31

**Comment by adarsh-a-tw** [comment]
> Hey @adarsh-a-tw can you pls approve the workflow so i can test it? #31

Done!
