### ISSUE TITLE
Implement standard set operations

### ISSUE THREAD

**Issue by adarsh-a-tw** [gopinathr143/go-collections#30]
Extend functionality of `Set` by adding the following methods.

- Union(s1, s2) -> returns a new set as the union of both sets
- Intersection(s1, s2) -> returns a new set with elements that exist in both sets
- Difference(s1, s2) -> returns a new set with the elements that exists in s1 but not in s2

**Comment by adarsh-a-tw** [comment]
@zegabr You can pick up this issue now.

**Comment by zegabr** [comment]
Thanks @adarsh-a-tw, I'm on it.

Could you please assign it to me?
