### ISSUE TITLE
[FEAT] Improve performance by passing the collection structures by reference on Size() and String() methods.

### ISSUE THREAD

**Issue by zegabr** [gopinathr143/go-collections#33]
**Is your feature request related to a problem? Please describe.**
I noticed some methods in the code were declared as 
`func (o Object) DoSomething(...` 
and some were  as 
`func (o *Object) DoSomething(...`.

While searching about value vs pointer receivers, I found out that in the first case, the code will be creating a copy of the structure, instead of just using the reference for it.

This could lead to low performance in cases where, for example, you have a very big [List[T]](https://github.com/gopher-utils/go-collections/blob/main/list.go) and you need to call [List.Size()](https://github.com/gopher-utils/go-collections/blob/main/list.go#L162) many times. Since it will keep creating copies of the List, every Size() call would take linear time and space complexity.

To be more specific, this would happen for Size() and String() operations for the collections already implemented (List and Set).

**Describe the solution you'd like**
To solve this problem, it is only needed to pass the collection by reference unless a copy is really necessary and there's no need to modify it.

**Comment by adarsh-a-tw** [comment]
@zegabr This will not cause performance issues because slices and maps are by default copied by their pointer values, and so they act like reference types.

However, since other functions are implemented to use pointer receivers, to make things uniform, we can make these functions use pointer receivers. Let me know if you are interested in making this change. I will assign it to you.

**Comment by zegabr** [comment]
@adarsh-a-tw Oh, I see. I didn't know that maps and slices were passed by pointer.

And yes, you can assign that to me too :)

**Comment by zegabr** [comment]
@adarsh-a-tw If possible, please add the `hacktoberfest` label on this too.
